### ISSUE TITLE
Support active/inactive color

### ISSUE THREAD

**Issue by manateelazycat** [tautologyclub/feebleline#28]
Hi, your plugin is awesome, i have use it instead my https://www.emacswiki.org/emacs/MiniBufferTray

It will be cool if this plugin support active/inactive color like below:
```
(custom-set-faces
 '(mode-line ((t (:background "darkred" :foreground "darkred" :height 0.1))))
 '(mode-line-inactive ((t (:background "gray10" :foreground "gray10" :height 0.1))))
)
```

I have test above code after load feebleline plugin, but active color won't work.

**Comment by tautologyclub** [comment]
Hi, thanks for the praise. Feebleline doesn't actually use the mode-line except if you're on emacs < 25...

**Comment by tautologyclub** [comment]
By the way, this feature basically comes down to a matter of priorities - you can implement the message function slightly differently, which makes it so that the feebleline message is only visible in the focused frame. But that has the drawback that the echo area flickers each time feebleline is updated, which is very annoying. If you think that won't bother you, you can look at the earlier revisions of feebleline to get some inspiration.
